### ISSUE TITLE
SyntaxError from notifiers_cli

### ISSUE THREAD

**Issue by lukedoomer** [liiight/notifiers#75]
python3.5
pip3 install notifiers

> 

```
root@server:~# notifiers
Traceback (most recent call last):
  File "/usr/local/bin/notifiers", line 7, in <module>
    from notifiers_cli.core import entry_point
  File "/usr/local/lib/python3.5/dist-packages/notifiers_cli/core.py", line 72
    click.echo(f"Name: '{name}', Schema: {schema}")
                                                 ^
SyntaxError: invalid syntax
```

**Comment by liiight** [comment]
minimal python version is 3.6, I should enforce that.
You can install via docker though
